### ISSUE TITLE
(RFUtilities-1.10.2-0.2.jar) crashes dedicated Forge 1.10.2 build 2120 on startup

### ISSUE THREAD

**Issue by kreezxil** [XFactHD/RFUtilities#11]
Issue:  rfutilities{1.10.2-0.1-hotfix2} [RFUtilities] (RFUtilities-1.10.2-0.2.jar) crashes dedicated Forge 1.10.2 build 2120 on startup

Notes:
     Looks like invalid side server

crash report:
https://gist.github.com/4ed72fe5233e9356dab858f288e0da2c

fml server latest:
https://gist.github.com/56c31cb18ca55d8092cfd82fbd12b668

**Comment by XFactHD** [comment]
The game is trying to load a client class on the server, I will look into this as soon as possible.

**Comment by XFactHD** [comment]
Sorry that it took so long, school got in the way. The bug is now fixed and the file about to be approved on curse.
