### ISSUE TITLE
placement crash

### ISSUE THREAD

**Issue by stclaus4** [XFactHD/RFUtilities#13]
i paced the octadic enderio capacitor, or the thing that looks like it, instantly crashed
http://pastebin.com/hRyQD236 here is the log

**Comment by XFactHD** [comment]
Can you reproduce this without Dark Roleplay Medieval?

**Comment by stclaus4** [comment]
ill see

**Comment by stclaus4** [comment]
i removed dark roleplay, the rf capacitor worked but the transistor crashed it as i placed it

**Comment by stclaus4** [comment]
http://pastebin.com/EZ69PQtR

**Comment by XFactHD** [comment]
I'll look into it once I am back at the computer.

**Comment by stclaus4** [comment]
ok, looks like a really cool mod. hope to figure out how it works soon

**Comment by XFactHD** [comment]
Can you try [this](https://www.dropbox.com/s/9eu7cgo3j8ljdd8/RFUtilities-1.10.2-0.3-hotfix1.jar?dl=0) version, please?

**Comment by stclaus4** [comment]
yeah that one seems to work seems to work. i needed to optimize my pack, the game seems to want 12GB of ram to run 130+ mods in 1.10.2

**Comment by XFactHD** [comment]
Ok, nice, thanks for the feedback.
