### ISSUE TITLE
Crash with Switch

### ISSUE THREAD

**Issue by ExcitedName** [XFactHD/RFUtilities#6]
First of all. Nice work. Sadly I had an issue with your switch. I had power flowing through it using Ender Io conduits. When I right mouse clicked on it with another switch in my hand...crash. It is pertaining to the Thermal Expansion wrench. I have Thermal Foundation and Ender Io but not Thermal Expansion.
http://pastebin.com/MqxPx4vh

**Comment by XFactHD** [comment]
Thanks for the compliment 😏.
I will look into this ASAP.

**Comment by XFactHD** [comment]
New version is about to be approved on Curse.

**Comment by ExcitedName** [comment]
Wow, that was fast. Thanks.
