### ISSUE TITLE
Crash on Start up 

### ISSUE THREAD

**Issue by DurasZess** [XFactHD/RFUtilities#8]
RFUtilities-1.10.2-0.1
Minecraft 1.10.2
Forge 1.10.2-12.18.1.2018

my crash report  at start up. i hope it helps 

[crash-2016-08-29_16.22.33-client.txt](https://github.com/XFactHD/RFUtilities/files/442585/crash-2016-08-29_16.22.33-client.txt)

**Comment by XFactHD** [comment]
Found and fixed the issue, getting a new version ready right now.

**Comment by XFactHD** [comment]
New version is up and ready for download.
